### ISSUE TITLE
Update the photos.

### ISSUE THREAD

**Issue by anuragxel** [mounikasomisetty/StudentKit2015#3]
Self Explanatory.

**Comment by anuragxel** [comment]
Update the photos on the slides with nice ones.

**Comment by gvishal** [comment]
This is done, right?

**Comment by gvishal** [comment]
Some of the photos are look downsampled.

**Comment by anuragxel** [comment]
haan, the slides ka photos look bad. We need to fix that. Also, some of the photos in the slides are not updated.

Lastly, need to increase JPEG compression for the files to use minimal bandwidth (but that's last).
