### ISSUE TITLE
Updating the letters.

### ISSUE THREAD

**Issue by SilentFlame** [mounikasomisetty/StudentKit2015#9]
- [x] Apex's
- [x] SLC's
- [x] Director's
- [ ] Dean Academics

**Comment by anuragxel** [comment]
apex is done

**Comment by SilentFlame** [comment]
@anuragxel 
Is it merged here?
As I have edited the .html file.
should I send a PR?

**Comment by anuragxel** [comment]
I did it yesterday. the apex letter as an example. Do the other ones.

**Comment by anuragxel** [comment]
Also, there's no letter by Dean Academics, AFAIK.

**Comment by SilentFlame** [comment]
Yeah  I saw that.

anyone assigned to it?

**Comment by anuragxel** [comment]
Assigned to what ?

**Comment by SilentFlame** [comment]
to get the letters from concerned people?

**Comment by anuragxel** [comment]
okay, so Sneha uploaded the letters in markdown format on the Facebook group (if you would bestow the kindness to scroll up and check). All the information that needs to be updated is there on that facebook group (barring any changes, which Sneha is communicating with SLC). Just put the information in those markdown files into the respective HTML files. 

The Dean Academics doesn't write a letter, so we would not be asking for their letter. All other updated information is there with us on that Facebook group as mentioned.

**Comment by anuragxel** [comment]
Apparently, sneha also has sprung up into action, so you may look at the photos part of the website. Do you have enough info on that ?

**Comment by gvishal** [comment]
@anuragxel director's letter is removed?
